### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by jhxu003** [yangnianzu0515/MoleRec#1]
你好，我在尝试用GPU训练时遇到了这个问题：
```
WARNING:root:The OGB package is out of date. Your version is 1.3.5, while the latest version is 1.3.6.
Namespace(Test=False, coef=2.5, device=0, dim=64, dp=0.7, embedding=False, epochs=50, lr=0.0005, model_name='dim_64-lr_0.0005-coef_2.5-dp_0.7-ddi_0.06', resume_path=None, target_ddi=0.06)
131
[23:35:28] Explicit valence for atom # 0 N, 4, is greater than permitted
[SMILES] [H][N]([H])([H])[Pt]1(OC(=O)C2(CCC2)C(=O)O1)[N]([H])([H])[H]
[Error] Invalid smiles
Smiles Num:283
n_col:283
n_row:131
----------------Epoch 1------------------
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    Train(
  File "/public/home/jhxu/model/MoleRec-master/src/training.py", line 107, in Train
    result, loss_ddi = model(
  File "/public/home/jhxu/anaconda3/envs/MoleRec/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/jhxu/model/MoleRec-master/src/modules/MoleRec.py", line 105, in forward
    output1, hidden1 = self.seq_encoders[0](seq1)
  File "/public/home/jhxu/anaconda3/envs/MoleRec/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/jhxu/anaconda3/envs/MoleRec/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 837, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
看起来像是cuDNN无法使用，可能是因为cuda版本和torch版本不对应导致的，方便告诉我您的cuda版本是多少吗。
您在训练的过程中有遇到这个情况吗，能否向您请教一下该如何解决

**Comment by jhxu003** [comment]
解决了，加了这行代码就可以了
`torch.backends.cudnn.enabled=False`

**Comment by yangnianzu0515** [comment]
Hello, first of all, thank you for your interest! We have already provided our environment configuration in the "[MoleRec.yml](https://github.com/yangnianzu0515/MoleRec/blob/master/MoleRec.yml)" file within this repository.

We are pleased to see that you have already resolved your issue! If you have any further questions or need assistance in the future, please feel free to reach out to us!
